manifest:
  remotes:
    - name: zmk
      url-base: https://github.com/zmk_firmware
    - name: urob
      url-base: https://github.com/urob
    - name: jbarr21
      url-base: https://github.com/jbarr21
  projects:
    - name: zmk
      remote: urob
      revision: e0beb14cc9243823abf630749fac0cf125113f6d
      import: app/west.yml
  self:
    path: config
