manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: lowprokb
      url-base: https://github.com/LOWPROKB
  projects:
    - name: zmk
      remote: lowprokb
      revision: corne-ish-zen-v2
      import: app/west.yml
  self:
    path: config
