on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    uses: urob/zmk/.github/workflows/build-user-config.yml@build-with-submodules

  # render:
  #   uses: jbarr21/keymap-display/.github/workflows/render-keymap.yml@main
  #   with:
  #     output_type: kle
  #     keymap_type: nf
  #     keymap_path: config/3x5.dtsi
